export type WorkCategory =
  | "ブランディング"
  | "EC/Shopify"
  | "Web制作"
  | "PR/広告"
  | "リサーチ"
  | "コミュニティ"
  | "事業開発"
  | "DX推進"
  | "コンテンツ"
  | "デザイン"
  | "イベント"
  | "コンサルティング"

export type WorkProject = {
  id: string
  title: string
  client: string | null
  year: number
  endYear?: number | "継続中"
  categories: WorkCategory[]
  role: string
  highlight: string | null
  externalUrl: string | null
  isFeatured: boolean
  featuredSize?: "large" | "medium"
  featuredGradient?: [string, string] // [from, to] hex colors
  saiComment?: string // サイの寄り道コメント
}

export const CATEGORY_COLORS: Record<WorkCategory, string> = {
  "ブランディング": "#2563eb",
  "EC/Shopify": "#059669",
  "Web制作": "#7c3aed",
  "PR/広告": "#dc2626",
  "リサーチ": "#0891b2",
  "コミュニティ": "#ea580c",
  "事業開発": "#4f46e5",
  "DX推進": "#0d9488",
  "コンテンツ": "#9333ea",
  "デザイン": "#e11d48",
  "イベント": "#ca8a04",
  "コンサルティング": "#6366f1",
}

export const works: WorkProject[] = [
  // === Featured ===
  {
    id: "bcg-geniac",
    title: "GENIAC",
    client: "BCG × 経済産業省 / NEDO",
    year: 2023,
    endYear: "継続中",
    categories: ["コミュニティ", "イベント", "コンサルティング"],
    role: "国家プロジェクトのコミュニティ設計・運営",
    highlight: "生成AI基盤モデル開発企業20社のコミュニティを設計。マッチングイベント来場者130名、PoC移行案件を創出",
    externalUrl: null,
    saiComment: "国のAI戦略会議なのに、懇親会のケータリング選びにいちばん本気だった",
    isFeatured: true,
    featuredSize: "large",
    featuredGradient: ["#0c1a3d", "#1e3a8a"],
  },
  {
    id: "wazao-ippon",
    title: "WAZAO-IPPON",
    client: "自社ブランド",
    year: 2020,
    endYear: "継続中",
    categories: ["ブランディング", "EC/Shopify", "コンテンツ"],
    role: "和竿文化を次世代へ繋ぐブランドの全て",
    highlight: "世界初の渓流ルアー専用和竿「Inheritor」を開発。Instagram 6,700+フォロワー、イタリア25%",
    saiComment: "なんなら釣れなくてもいい。釣りは手段で、和竿は旗",
    externalUrl: "https://wazao-ippon.com/",
    isFeatured: true,
    featuredSize: "medium",
    featuredGradient: ["#5c2d0e", "#92400e"],
  },
  {
    id: "chuo-dept",
    title: "大宮門街",
    client: "中央デパート",
    year: 2020,
    endYear: "継続中",
    categories: ["ブランディング", "PR/広告", "事業開発"],
    role: "再開発から蕎麦屋まで。まちの文化装置をつくる",
    highlight: "PRTimes ランキング1位（21,000PV超）。SHABA蕎麦のコンセプト設計からオープンまで伴走",
    saiComment: "再開発のPMをやってたら、いつの間にか蕎麦を打ってた",
    externalUrl: null,
    isFeatured: true,
    featuredSize: "medium",
    featuredGradient: ["#1a1a2e", "#334155"],
  },

  // === 主要クライアント ===
  {
    id: "hakuhodo",
    title: "博報堂パートナーシップ",
    client: "博報堂 BID局",
    year: 2020,
    endYear: "継続中",
    categories: ["リサーチ", "ブランディング", "コンサルティング"],
    role: "リサーチ・WS設計・コンセプト開発",
    highlight: "26案件・6年超の継続取引。ロッテ、SHIMANO、ミツカン、日本香堂などのブランド戦略を支援",
    saiComment: "「また森さんから電話だよ」が、6年間のいちばんの褒め言葉",
    externalUrl: null,
    isFeatured: false,
  },
  {
    id: "toei",
    title: "全社DX推進",
    client: "東栄運輸",
    year: 2020,
    endYear: 2022,
    categories: ["DX推進", "Web制作", "事業開発"],
    role: "副社長管轄「社長室」として経営課題に伴走",
    highlight: "Web制作、採用支援、ドローン新規事業、VR旅行企画、システム基盤刷新まで6領域を横断",
    saiComment: "観光バスの会社に入ったはずが、気づいたらドローンでハチの巣を駆除してた",
    externalUrl: null,
    isFeatured: false,
  },
  {
    id: "infas",
    title: "WWDJAPAN 広告営業",
    client: "INFASパブリケーションズ",
    year: 2025,
    endYear: "継続中",
    categories: ["PR/広告", "コンサルティング", "イベント"],
    role: "広告営業チームの実務遂行・主要アカウント担当",
    highlight: "ZOZO、New Balance、COACH、ラルフローレン等の主要アカウントを担当",
    saiComment: "ファッションの最前線にサイが立つ日が来るとは",
    externalUrl: null,
    isFeatured: false,
  },
  {
    id: "naigai",
    title: "メディア事業支援",
    client: "内外出版社",
    year: 2023,
    endYear: "継続中",
    categories: ["コンサルティング", "コンテンツ", "EC/Shopify"],
    role: "経営コンサルから事業支援へ。YouTube・EC・営業の仕組み化",
    highlight: "月額15万円→50万円+EC売上20%に契約拡大。ジパングツーリズムのマルチメディア企画",
    saiComment: "釣り雑誌とバイク雑誌とクルマ雑誌。趣味の匂いしかしない",
    externalUrl: null,
    isFeatured: false,
  },
  {
    id: "mdxq",
    title: "マナビDX Quest",
    client: "経済産業省（博報堂→BCG→SIGNATE）",
    year: 2022,
    endYear: "継続中",
    categories: ["コミュニティ", "イベント", "コンテンツ"],
    role: "2,000〜3,000名規模のデジタル人材育成コミュニティを設計・運営",
    highlight: "4年連続担当。発注元が変わっても継続される信頼関係",
    saiComment: "発注元が3回変わっても呼ばれ続ける。居心地の良さは罪",
    externalUrl: null,
    isFeatured: false,
  },
  {
    id: "dnp",
    title: "未来創造ラボ PR",
    client: "大日本印刷",
    year: 2023,
    endYear: 2024,
    categories: ["ブランディング", "PR/広告", "コンサルティング"],
    role: "XR事業ユニットのブランディング戦略策定・PR支援",
    highlight: "メタバース役所、セキュリティ研修などXRソリューションの組織ブランディング",
    saiComment: "未来を創るラボの名前を考えるのは、なかなか未来的な仕事だった",
    externalUrl: null,
    isFeatured: false,
  },
  {
    id: "hacosco",
    title: "XR事業伴走",
    client: "ハコスコ",
    year: 2019,
    endYear: 2024,
    categories: ["事業開発", "DX推進", "コンサルティング"],
    role: "経営支援、NEC向けVR開発、メタストアPMO",
    highlight: "5年間の経営伴走。VR同時再生システム開発やメタストアPMOなどXR領域を包括支援",
    saiComment: "VRの中でサイに乗れる日を5年待ってる",
    externalUrl: null,
    isFeatured: false,
  },
  {
    id: "kozushima",
    title: "まるっと！神津島",
    client: "合同会社FamiliA",
    year: 2023,
    endYear: "継続中",
    categories: ["PR/広告", "Web制作", "コンサルティング"],
    role: "観光アプリの広報・マーケティング・助成金申請",
    highlight: "GPS連動音声ガイド+すごろくゲームの観光アプリ。グッドデザイン賞応募",
    saiComment: "島にはサイはいないけど、サイの心はある",
    externalUrl: null,
    isFeatured: false,
  },
  {
    id: "matcha",
    title: "営業支援・インバウンド調査",
    client: "MATCHA",
    year: 2023,
    endYear: 2024,
    categories: ["コンサルティング", "リサーチ"],
    role: "営業WF改善、三井ガーデンホテル4ヶ国インバウンド調査",
    highlight: "4ヶ国（米・中・台・韓）の定量+16名定性調査で戦略構築",
    saiComment: "ホテルの朝食の写真を4ヶ国語で議論する日々",
    externalUrl: null,
    isFeatured: false,
  },
  {
    id: "sake-hundred",
    title: "デジタル広告クリエイティブ",
    client: "SAKE HUNDRED",
    year: 2022,
    categories: ["PR/広告", "コンテンツ", "デザイン"],
    role: "高級日本酒ブランドの動画・バナー広告制作",
    highlight: null,
    saiComment: "一杯数万円の日本酒を撮影用に開けるときの緊張感",
    externalUrl: null,
    isFeatured: false,
  },
  {
    id: "fishlle",
    title: "Fishlle! リブランディング",
    client: "iiinc",
    year: 2022,
    endYear: 2023,
    categories: ["ブランディング", "デザイン"],
    role: "未利用魚サブスクのブランド再構築",
    highlight: "ブランドアイデンティティガイド+イラストマニュアルを納品",
    saiComment: "捨てられる魚を救うブランドを、サイが救った",
    externalUrl: null,
    isFeatured: false,
  },
  {
    id: "s-consulting-hamilton",
    title: "Hamilton ブランド戦略",
    client: "Sコンサルティング",
    year: 2023,
    endYear: "継続中",
    categories: ["ブランディング", "リサーチ", "コンサルティング"],
    role: "ベビーカーブランドの市場調査・ポジショニング・世界観設計",
    highlight: "初年度目標400台、3年で年商1億円のブランド戦略を策定",
    saiComment: "ベビーカーを押すサイの絵が脳裏から離れない",
    externalUrl: null,
    isFeatured: false,
  },
  {
    id: "decillion",
    title: "A PLACE APART",
    client: "Decillion Capital",
    year: 2025,
    endYear: "継続中",
    categories: ["ブランディング", "デザイン", "コンサルティング"],
    role: "富裕層向け会員制プラットフォームのブランディング",
    highlight: null,
    saiComment: "ヘリとヨットとジェットの話をしながら、電車で帰った",
    externalUrl: null,
    isFeatured: false,
  },
  {
    id: "kakunoshin",
    title: "ペットフード新規事業",
    client: "格之進",
    year: 2023,
    categories: ["事業開発", "ブランディング", "コンサルティング"],
    role: "高級ハンバーグブランドからペットフード事業へ。PoC実行支援",
    highlight: null,
    saiComment: "A5ランクの肉を知ってるからこそ作れるドッグフード、という説得力",
    externalUrl: null,
    isFeatured: false,
  },
  {
    id: "suminoe",
    title: "RETANGO EC構築",
    client: "スミノエ",
    year: 2022,
    categories: ["EC/Shopify", "コンサルティング"],
    role: "大手繊維メーカーのECブランド立ち上げをShopifyで包括支援",
    highlight: null,
    saiComment: "カーペットの原価構造を理解するところから始まったEC構築",
    externalUrl: null,
    isFeatured: false,
  },
  {
    id: "raphael",
    title: "小麦の禁断症状",
    client: "ラファエル",
    year: 2022,
    categories: ["ブランディング", "デザイン", "Web制作"],
    role: "カレーパンブランドの名前・ロゴ・パッケージ・Web・倉庫まで一気通貫",
    highlight: null,
    saiComment: "ブランド名を考えてたら倉庫の鍵を渡された",
    externalUrl: null,
    isFeatured: false,
  },
  {
    id: "okashi-ec",
    title: "お菓子EC + サニタス進学ラボ",
    client: "カーテン社",
    year: 2022,
    endYear: 2023,
    categories: ["EC/Shopify", "Web制作"],
    role: "1社から6つのWebプロダクトを横断支援",
    highlight: null,
    saiComment: "お菓子のECを作ってたら柔道整復師の学校検索サイトも作ることになった",
    externalUrl: null,
    isFeatured: false,
  },
  {
    id: "nappalm",
    title: "nappalm / LIFE NEIGHBOR",
    client: "nappalm",
    year: 2019,
    endYear: 2021,
    categories: ["ブランディング", "事業開発", "デザイン"],
    role: "アメカジブランドの事業計画から助成金申請まで包括支援",
    highlight: null,
    saiComment: "「俺のアメカジ」というブランド名を大真面目に議論した夜",
    externalUrl: null,
    isFeatured: false,
  },
  {
    id: "bff",
    title: "cabconfriends VI",
    client: "BFF",
    year: 2021,
    categories: ["ブランディング", "デザイン"],
    role: "キャンピングカーレンタルのVI一式（48ファイル）",
    highlight: null,
    saiComment: "48パターンのロゴを作って、犬とキャンピングカーに愛着が湧いた",
    externalUrl: null,
    isFeatured: false,
  },
  {
    id: "soka-kenko",
    title: "施設フォトグラメトリ",
    client: "草加健康センター",
    year: 2020,
    categories: ["コンテンツ", "DX推進"],
    role: "ドローン空撮630カット+地上撮影222カット。3Dスキャン用素材制作",
    highlight: null,
    saiComment: "ラッコバスを852枚撮った。ラッコの気持ちがわかった気がする",
    externalUrl: null,
    isFeatured: false,
  },
  {
    id: "manaka",
    title: "間｜MA メディア",
    client: "まなか",
    year: 2026,
    endYear: "継続中",
    categories: ["ブランディング", "Web制作", "コンテンツ"],
    role: "「間」をテーマに内省の文化を現代に翻訳するWebメディア企画・公開",
    highlight: null,
    saiComment: "効率の反対語を探す仕事。見つかったのは「間」だった",
    externalUrl: null,
    isFeatured: false,
  },
  {
    id: "tsukiji",
    title: "築地まちづくりPJ",
    client: "SSU / 築地まちづくり株式会社",
    year: 2026,
    endYear: "継続中",
    categories: ["ブランディング", "コンテンツ", "コンサルティング"],
    role: "三井不動産・トヨタ不動産・読売新聞による築地再開発のコンセプト策定",
    highlight: null,
    saiComment: "築地の未来を考えるのに、まず寿司を食べに行った",
    externalUrl: null,
    isFeatured: false,
  },
  {
    id: "tokyo",
    title: "子供の遊び推進PJ",
    client: "東京都",
    year: 2024,
    categories: ["コンサルティング", "事業開発"],
    role: "NPOプレーパークせたがやとの協業で東京都公募事業に応札",
    highlight: null,
    saiComment: "子供の遊びを大人が真剣に企画する。それ自体がもう遊びだった",
    externalUrl: null,
    isFeatured: false,
  },
  {
    id: "eito",
    title: "高校生 × 和竿マーケ",
    client: "栄東中学・高等学校",
    year: 2021,
    categories: ["コンサルティング", "イベント"],
    role: "WAZAO-IPPONを題材に高校生がSNSマーケ施策を企画→最優秀案を実行",
    highlight: null,
    saiComment: "高校生に和竿のマーケを任せたら、大人より鋭い施策が出てきた",
    externalUrl: null,
    isFeatured: false,
  },
  {
    id: "tsukanoma",
    title: "ツカノマノスゴイサウナ",
    client: "自社事業",
    year: 2019,
    categories: ["イベント", "ブランディング"],
    role: "渋谷の取り壊しビル屋上で4ヶ月限定サウナイベント",
    highlight: "700名以上を動員",
    saiComment: "壊されるビルの屋上で、いちばん熱い思い出をつくった",
    externalUrl: null,
    isFeatured: false,
  },
  {
    id: "not-a-hotel",
    title: "Not A Bus 企画",
    client: "NOT A HOTEL",
    year: 2022,
    categories: ["事業開発", "コンサルティング"],
    role: "都内バス型移動ホテルの企画提案",
    highlight: null,
    saiComment: "2階建てバスに風呂をつける提案を、全員が真顔で聞いてた",
    externalUrl: null,
    isFeatured: false,
  },
  {
    id: "malaika",
    title: "Shopify EC構築",
    client: "マライカ",
    year: 2022,
    categories: ["EC/Shopify", "Web制作"],
    role: "エスニック雑貨ECサイト構築（ポイント・楽天連携・複数条件検索）",
    highlight: null,
    saiComment: "世界中の雑貨の検索条件を考えるのは、世界一周みたいだった",
    externalUrl: null,
    isFeatured: false,
  },
  {
    id: "ichoosr",
    title: "日本市場ブランドチューニング",
    client: "iChoosr Japan",
    year: 2026,
    categories: ["ブランディング", "リサーチ"],
    role: "オランダ発ソーラーパネル共同購入PFの日本向けブランド設計",
    highlight: null,
    saiComment: "太陽光パネルをみんなで買う文化を、日本語で説明する難しさ",
    externalUrl: null,
    isFeatured: false,
  },
]

export const ALL_CATEGORIES: WorkCategory[] = [
  "ブランディング",
  "コンサルティング",
  "リサーチ",
  "コミュニティ",
  "事業開発",
  "DX推進",
  "EC/Shopify",
  "Web制作",
  "PR/広告",
  "イベント",
  "コンテンツ",
  "デザイン",
]
